sonar.projectKey=devops-project-bca_smart-logistics-frontend1
sonar.organization=devops-project-bca
<<<<<<< HEAD
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,build/**,dist/**
sonar.qualitygate.wait=false
=======


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=smart-logistics-frontend1
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
>>>>>>> 9f0060abb3dd065f322878a79223d3f5b1ec2b37
